TARGER = ./main.out
SRCS = \
	./src/main.c\
	./src/table/*
.PHONY: all, build, clean, run

$(TARGER):
	gcc $(SRCS) -o $(TARGER)

all: clean build
build: $(TARGER)

clean:
	rm -rf $(TARGER)
run:
	$(TARGER)
