#ifndef STATUS_CODES_H
#define STATUS_CODES_H


enum Status{
    SUCCESS = 0,
    INVALID_FILE_HEADER_WIN,
    FILE_MAPPING_ERROR,
    SET_FILE_POINTER_ERROR,
    SET_END_OF_FILE_ERROR,
    INVALID_FILE_DESCRIPTOR,
    ERROR_EXPAND_FILE,
    NPE,
    TOO_BIG_FILE,
    ALLIGNMENT_ERROR,
    MAP_ERROR_LIN,
    TOO_BIG_OFFSET,
    NO_SUCH_TABLE,
    ALL_DATA_READ,
    NO_SUCH_OPERAND_NAME,
    TYPES_NOT_COMPARABLE
};

#define checkForErr(Y) if(Y != 0) {return Y;}
#endif
